import { journeyContent } from "./journeyContent";
import { journeyImagePaths } from "./journeyImages";

export type JourneySummary = {
  slug: string;
  title: string;
  duration: string;
  difficulty: "introductory" | "intermediate" | "deep";
  image: string;
  description: string;
};

export const journeyCatalog: JourneySummary[] = [
  {
    slug: "james-deep",
    title: "James: 10 Days Deep",
    duration: "10 Days",
    difficulty: "intermediate",
    image: journeyImagePaths["james-deep"],
    description:
      "James writes to a scattered church, people who claimed faith but lived differently from Monday to Saturday. His letter is less a theology lecture and more a direct conversation: you say you believe. Does your life show it?",
  },
  {
    slug: "still",
    title: "Still: 21 Days of Contemplative Prayer",
    duration: "21 Days",
    difficulty: "introductory",
    image: journeyImagePaths.still,
    description:
      "Most of us talk at God. This journey teaches you to sit with God. Twenty-one days of building a contemplative prayer practice, starting with just two minutes of silence and gradually deepening into a rhythm that changes how you experience God's presence.",
  },
  {
    slug: "the-examen",
    title: "The Examen: 14 Days of Evening Reflection",
    duration: "14 Days",
    difficulty: "introductory",
    image: journeyImagePaths["the-examen"],
    description:
      "The Examen is a five-hundred-year-old prayer practice from Ignatius of Loyola. It is simple: at the end of each day, look back and notice where God showed up, and where you missed it. Fourteen days to build the habit of paying attention.",
  },
  {
    slug: "rooted",
    title: "Rooted: 30 Days in the Psalms",
    duration: "30 Days",
    difficulty: "introductory",
    image: journeyImagePaths.rooted,
    description:
      "The Psalms are the prayer book of the Bible, raw, honest, and deeply human. This thirty-day journey pairs one psalm per day with a contemplative reading practice. Some days you will sit in praise. Others, you will wrestle with doubt. That is the point.",
  },
  {
    slug: "way-of-jesus",
    title: "The Way of Jesus: 40 Days Through the Gospels",
    duration: "40 Days",
    difficulty: "deep",
    image: journeyImagePaths["way-of-jesus"],
    description:
      "Forty days walking through the life and teachings of Jesus, from his first sermon to his last words. Each day pairs a Gospel passage with an application challenge. Because understanding what Jesus said without doing what he said is the whole problem.",
  },
  {
    slug: "new-believer",
    title: "First Steps: A New Believer Journey",
    duration: "21 Days",
    difficulty: "introductory",
    image: journeyImagePaths["new-believer"],
    description:
      "The first weeks after saying yes to Jesus are some of the most important and most vulnerable. This twenty-one day journey gives you a steady path for those first steps.",
  },
  {
    slug: journeyContent.leadership.slug,
    title: journeyContent.leadership.title,
    duration: journeyContent.leadership.duration,
    difficulty: journeyContent.leadership.difficulty,
    image: journeyImagePaths.leadership,
    description: journeyContent.leadership.description,
  },
  {
    slug: journeyContent.love.slug,
    title: journeyContent.love.title,
    duration: journeyContent.love.duration,
    difficulty: journeyContent.love.difficulty,
    image: journeyImagePaths.love,
    description: journeyContent.love.description,
  },
  {
    slug: journeyContent.money.slug,
    title: journeyContent.money.title,
    duration: journeyContent.money.duration,
    difficulty: journeyContent.money.difficulty,
    image: journeyImagePaths.money,
    description: journeyContent.money.description,
  },
  {
    slug: journeyContent.health.slug,
    title: journeyContent.health.title,
    duration: journeyContent.health.duration,
    difficulty: journeyContent.health.difficulty,
    image: journeyImagePaths.health,
    description: journeyContent.health.description,
  },
  {
    slug: journeyContent["fear-anxiety"].slug,
    title: journeyContent["fear-anxiety"].title,
    duration: journeyContent["fear-anxiety"].duration,
    difficulty: journeyContent["fear-anxiety"].difficulty,
    image: journeyImagePaths["fear-anxiety"],
    description: journeyContent["fear-anxiety"].description,
  },
  {
    slug: journeyContent.marriage.slug,
    title: journeyContent.marriage.title,
    duration: journeyContent.marriage.duration,
    difficulty: journeyContent.marriage.difficulty,
    image: journeyImagePaths.marriage,
    description: journeyContent.marriage.description,
  },
  {
    slug: journeyContent.parenting.slug,
    title: journeyContent.parenting.title,
    duration: journeyContent.parenting.duration,
    difficulty: journeyContent.parenting.difficulty,
    image: journeyImagePaths.parenting,
    description: journeyContent.parenting.description,
  },
  {
    slug: journeyContent.purpose.slug,
    title: journeyContent.purpose.title,
    duration: journeyContent.purpose.duration,
    difficulty: journeyContent.purpose.difficulty,
    image: journeyImagePaths.purpose,
    description: journeyContent.purpose.description,
  },
  {
    slug: journeyContent.identity.slug,
    title: journeyContent.identity.title,
    duration: journeyContent.identity.duration,
    difficulty: journeyContent.identity.difficulty,
    image: journeyImagePaths.identity,
    description: journeyContent.identity.description,
  },
  {
    slug: journeyContent.forgiveness.slug,
    title: journeyContent.forgiveness.title,
    duration: journeyContent.forgiveness.duration,
    difficulty: journeyContent.forgiveness.difficulty,
    image: journeyImagePaths.forgiveness,
    description: journeyContent.forgiveness.description,
  },
  {
    slug: journeyContent.prayer.slug,
    title: journeyContent.prayer.title,
    duration: journeyContent.prayer.duration,
    difficulty: journeyContent.prayer.difficulty,
    image: journeyImagePaths.prayer,
    description: journeyContent.prayer.description,
  },
  {
    slug: journeyContent["faith-doubt"].slug,
    title: journeyContent["faith-doubt"].title,
    duration: journeyContent["faith-doubt"].duration,
    difficulty: journeyContent["faith-doubt"].difficulty,
    image: journeyImagePaths["faith-doubt"],
    description: journeyContent["faith-doubt"].description,
  },
  {
    slug: journeyContent["work-ambition"].slug,
    title: journeyContent["work-ambition"].title,
    duration: journeyContent["work-ambition"].duration,
    difficulty: journeyContent["work-ambition"].difficulty,
    image: journeyImagePaths["work-ambition"],
    description: journeyContent["work-ambition"].description,
  },
  {
    slug: journeyContent.grief.slug,
    title: journeyContent.grief.title,
    duration: journeyContent.grief.duration,
    difficulty: journeyContent.grief.difficulty,
    image: journeyImagePaths.grief,
    description: journeyContent.grief.description,
  },
  {
    slug: journeyContent.friendship.slug,
    title: journeyContent.friendship.title,
    duration: journeyContent.friendship.duration,
    difficulty: journeyContent.friendship.difficulty,
    image: journeyImagePaths.friendship,
    description: journeyContent.friendship.description,
  },
  {
    slug: journeyContent.anger.slug,
    title: journeyContent.anger.title,
    duration: journeyContent.anger.duration,
    difficulty: journeyContent.anger.difficulty,
    image: journeyImagePaths.anger,
    description: journeyContent.anger.description,
  },
  {
    slug: journeyContent.wisdom.slug,
    title: journeyContent.wisdom.title,
    duration: journeyContent.wisdom.duration,
    difficulty: journeyContent.wisdom.difficulty,
    image: journeyImagePaths.wisdom,
    description: journeyContent.wisdom.description,
  },
  {
    slug: journeyContent.addiction.slug,
    title: journeyContent.addiction.title,
    duration: journeyContent.addiction.duration,
    difficulty: journeyContent.addiction.difficulty,
    image: journeyImagePaths.addiction,
    description: journeyContent.addiction.description,
  },
  {
    slug: journeyContent.gratitude.slug,
    title: journeyContent.gratitude.title,
    duration: journeyContent.gratitude.duration,
    difficulty: journeyContent.gratitude.difficulty,
    image: journeyImagePaths.gratitude,
    description: journeyContent.gratitude.description,
  },
  {
    slug: journeyContent.patience.slug,
    title: journeyContent.patience.title,
    duration: journeyContent.patience.duration,
    difficulty: journeyContent.patience.difficulty,
    image: journeyImagePaths.patience,
    description: journeyContent.patience.description,
  },
  {
    slug: journeyContent.courage.slug,
    title: journeyContent.courage.title,
    duration: journeyContent.courage.duration,
    difficulty: journeyContent.courage.difficulty,
    image: journeyImagePaths.courage,
    description: journeyContent.courage.description,
  },
  {
    slug: journeyContent.generosity.slug,
    title: journeyContent.generosity.title,
    duration: journeyContent.generosity.duration,
    difficulty: journeyContent.generosity.difficulty,
    image: journeyImagePaths.generosity,
    description: journeyContent.generosity.description,
  },
  {
    slug: journeyContent.rest.slug,
    title: journeyContent.rest.title,
    duration: journeyContent.rest.duration,
    difficulty: journeyContent.rest.difficulty,
    image: journeyImagePaths.rest,
    description: journeyContent.rest.description,
  },
  {
    slug: journeyContent.suffering.slug,
    title: journeyContent.suffering.title,
    duration: journeyContent.suffering.duration,
    difficulty: journeyContent.suffering.difficulty,
    image: journeyImagePaths.suffering,
    description: journeyContent.suffering.description,
  },
  {
    slug: journeyContent.legacy.slug,
    title: journeyContent.legacy.title,
    duration: journeyContent.legacy.duration,
    difficulty: journeyContent.legacy.difficulty,
    image: journeyImagePaths.legacy,
    description: journeyContent.legacy.description,
  },
];
