export type JourneyDay = {
  day: number;
  passage: string;
  theme: string;
  prompt: string;
};

export type JourneyStat = {
  label: string;
  value: string;
};

export type JourneyContent = {
  slug: string;
  title: string;
  duration: string;
  difficulty: "introductory" | "intermediate" | "deep";
  description: string;
  metaDescription: string;
  heroAlt: string;
  ctaLabel: string;
  stats: JourneyStat[];
  body: string[];
  days: JourneyDay[];
};

export const journeyContent = {
  leadership: {
    slug: "leadership",
    title: "Leadership: Leading from the Inside Out",
    duration: "21 Days",
    difficulty: "intermediate",
    description:
      "Leadership is less about charisma and more about formation. Twenty-one days on leading people, teams, and families without losing your soul in the process.",
    metaDescription:
      "Twenty-one days on servant leadership, wisdom, courage, and integrity for the people God has entrusted to you.",
    heroAlt: "Leadership: Leading from the Inside Out",
    ctaLabel: "Leadership",
    stats: [
      { label: "Duration", value: "21 Days" },
      { label: "Check-ins", value: "3 per day" },
      { label: "Focus", value: "Inside-out leadership" },
    ],
    body: [
      "Anybody can learn leadership tactics. Scripture is more interested in the person holding the responsibility. If your inner life is thin, eventually your leadership gets sharp, defensive, controlling, or exhausted. The problem is rarely just strategy. It is usually formation.",
      "This journey walks through the deeper curriculum of leadership in the Bible: humility, courage, listening, stewardship, multiplication, justice, endurance, and servant-hearted authority. Zoe will keep pushing the question beneath the question: not just what are you building, but who are you becoming while you build it?",
    ],
    days: [
      { day: 1, passage: "Mark 10:42-45", theme: "Servant First", prompt: "Who are you secretly trying to impress with your leadership right now?" },
      { day: 2, passage: "Proverbs 4:23", theme: "Guard the Source", prompt: "What leak in your inner life is already showing up in the way you lead?" },
      { day: 3, passage: "Exodus 18:13-23", theme: "Stop Playing Savior", prompt: "Where are you carrying more than God asked you to because delegating feels like losing control?" },
      { day: 4, passage: "James 1:19-20", theme: "Slow Mouth, Strong Presence", prompt: "In what room this week do you need to listen twice as long as you talk?" },
      { day: 5, passage: "1 Samuel 16:1-13", theme: "Hidden Anointing", prompt: "If nobody noticed your faithfulness for another year, would you still do the work well?" },
      { day: 6, passage: "Philippians 2:3-11", theme: "Downward Mobility", prompt: "What would humility look like in your leadership when you have actual power?" },
      { day: 7, passage: "Nehemiah 2:11-18", theme: "Vision With Tears", prompt: "What burden will not leave you alone? Maybe that ache is part of the assignment." },
      { day: 8, passage: "Luke 22:24-27", theme: "The Towel Before the Title", prompt: "Where do you want the recognition without the kind of service that earns trust?" },
      { day: 9, passage: "Proverbs 11:14", theme: "Counsel and Safety", prompt: "Who has permission to tell you you are wrong without you getting defensive?" },
      { day: 10, passage: "Psalm 78:70-72", theme: "Skill and Integrity", prompt: "Which matters more in your life right now: clean motives or competent execution, and why?" },
      { day: 11, passage: "1 Kings 3:5-12", theme: "A Listening Heart", prompt: "If you asked God for one thing for your leadership, would it be wisdom or just a better outcome?" },
      { day: 12, passage: "Galatians 6:9-10", theme: "When Applause Is Missing", prompt: "What good work are you tired of doing because nobody claps for it?" },
      { day: 13, passage: "Matthew 20:20-28", theme: "Ambition Redeemed", prompt: "What part of your ambition is holy, and what part is just hunger for applause?" },
      { day: 14, passage: "Ephesians 4:29-32", theme: "Words That Build", prompt: "Who under your care needs courage from your mouth more than critique?" },
      { day: 15, passage: "Numbers 11:10-17", theme: "Shared Spirit", prompt: "What would it look like to empower people instead of carrying everything yourself?" },
      { day: 16, passage: "2 Timothy 2:1-2", theme: "Multiplying More Than Tasks", prompt: "If someone copied your way of leading exactly, what kind of person would they become?" },
      { day: 17, passage: "Micah 6:8", theme: "Power and Justice", prompt: "Where have convenience and compassion started competing in your leadership?" },
      { day: 18, passage: "Acts 15:6-19", theme: "Prayer Before Strategy", prompt: "What hard conversation needs discernment before it needs another plan?" },
      { day: 19, passage: "1 Peter 5:1-4", theme: "Not Domineering", prompt: "Where are you managing people from fear instead of shepherding them with presence?" },
      { day: 20, passage: "Hebrews 12:1-3", theme: "Endurance Without Collapse", prompt: "What weight is slowing you down that is not actually yours to carry?" },
      { day: 21, passage: "John 13:1-17", theme: "The Basin and Towel", prompt: "Before you ask who should follow you, ask this: whose feet are you willing to wash?" },
    ],
  },
  love: {
    slug: "love",
    title: "Love: The Most Excellent Way",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Love is more than chemistry or niceness. Fourteen days on romantic love, sacrificial love, and loving difficult people without becoming fake or sentimental.",
    metaDescription:
      "Fourteen days on romantic love, sacrificial love, mercy, and learning to love difficult people like Jesus does.",
    heroAlt: "Love: The Most Excellent Way",
    ctaLabel: "Love",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Sincere love" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Most of us have strong opinions about love and surprisingly weak practices. We call neediness love. We call niceness love. We call attraction love. Scripture keeps cutting through all of that. Biblical love is sturdy, honest, costly, and personal.",
      "This journey moves through the many textures of love: delight, loyalty, sacrifice, truth-telling, mercy, tenderness, and enemy-love. Zoe will not let this stay abstract. Each day asks how love looks in your actual relationships, especially the ones that test you.",
    ],
    days: [
      { day: 1, passage: "1 Corinthians 13:1-7", theme: "More Than Chemistry", prompt: "Where does your version of love get loud but not kind?" },
      { day: 2, passage: "John 13:34-35", theme: "Love as Witness", prompt: "If someone judged Christianity by the way you love, what would they conclude?" },
      { day: 3, passage: "Song of Songs 2:10-13", theme: "Delight and Invitation", prompt: "What helps your heart open instead of brace?" },
      { day: 4, passage: "Ephesians 5:1-2", theme: "The Fragrance of Sacrifice", prompt: "Who gets the leftovers of you instead of the first and best of you?" },
      { day: 5, passage: "Ruth 1:16-17", theme: "Loyal Love", prompt: "Who have you promised to stay with when it stopped being easy?" },
      { day: 6, passage: "1 John 4:7-12", theme: "Loved First", prompt: "You cannot give what you refuse to receive. Where do you still resist being loved by God?" },
      { day: 7, passage: "Luke 10:25-37", theme: "Love Interrupts", prompt: "Who feels inconvenient to love right now?" },
      { day: 8, passage: "Hosea 2:14-20", theme: "Tenderness After Ruin", prompt: "What part of your story needs gentleness, not more self-punishment?" },
      { day: 9, passage: "Colossians 3:12-14", theme: "Put On Love", prompt: "Which piece of love do you keep taking off: patience, kindness, humility, forgiveness?" },
      { day: 10, passage: "Matthew 5:43-48", theme: "Difficult People", prompt: "Name the person you keep rehearsing arguments with in your head. What would love do next?" },
      { day: 11, passage: "John 15:9-13", theme: "Costly Friendship", prompt: "What comfort are you protecting that keeps you from loving deeply?" },
      { day: 12, passage: "1 Peter 4:8-10", theme: "Covers and Serves", prompt: "Can you tell the difference between covering in love and enabling in fear?" },
      { day: 13, passage: "1 Corinthians 16:13-14", theme: "Strength and Tenderness", prompt: "Where have you acted like you have to choose between backbone and love?" },
      { day: 14, passage: "Romans 12:9-18", theme: "Love Without Pretending", prompt: "What would sincere love look like in your actual Tuesday, not your ideal self?" },
    ],
  },
  money: {
    slug: "money",
    title: "Money & Wealth: Kingdom Economics",
    duration: "21 Days",
    difficulty: "intermediate",
    description:
      "Money reveals discipleship faster than most of us want to admit. Twenty-one days on stewardship, generosity, contentment, and building wealth without being owned by it.",
    metaDescription:
      "Twenty-one days on stewardship, generosity, contentment, and building wealth God's way without becoming captive to money.",
    heroAlt: "Money & Wealth: Kingdom Economics",
    ctaLabel: "Money & Wealth",
    stats: [
      { label: "Duration", value: "21 Days" },
      { label: "Check-ins", value: "3 per day" },
      { label: "Focus", value: "Stewardship and generosity" },
    ],
    body: [
      "Jesus talked about money all the time because money gets into trust, identity, fear, security, and power fast. A lot of financial pain is practical. A lot of it is spiritual. Usually it is both. Kingdom economics is not poverty theater or prosperity hype. It is freedom, stewardship, wisdom, generosity, and honest work under God's rule.",
      "This journey helps you face your money story without flinching. Zoe will walk through treasure, contentment, debt, planning, justice, generosity, and what it means to build with open hands. The goal is not guilt. It is a freer, truer relationship with what is in your hands.",
    ],
    days: [
      { day: 1, passage: "Matthew 6:19-24", theme: "The Treasure Test", prompt: "Follow your bank statement and calendar. What are they preaching about what you love most?" },
      { day: 2, passage: "Deuteronomy 8:10-18", theme: "Remember the Source", prompt: "Where have you started talking like your hustle is the whole story?" },
      { day: 3, passage: "Proverbs 3:9-10", theme: "Firstfruits", prompt: "What gets your first and best attention: God, bills, image, or fear?" },
      { day: 4, passage: "Luke 12:13-21", theme: "Bigger Barns", prompt: "What enough number keeps moving for you?" },
      { day: 5, passage: "2 Corinthians 9:6-11", theme: "Open-Handed Living", prompt: "When generosity pinches, what does it expose in you?" },
      { day: 6, passage: "Proverbs 13:11", theme: "Slow Wealth", prompt: "What part of you still wants the shortcut?" },
      { day: 7, passage: "1 Timothy 6:6-10", theme: "Rich Enough to Drift", prompt: "What desire is pretending to be a need?" },
      { day: 8, passage: "Acts 20:35", theme: "More Blessed to Give", prompt: "Do you actually believe giving could make you freer?" },
      { day: 9, passage: "Luke 16:10-13", theme: "Faithful With Little", prompt: "How do you handle small amounts when nobody is looking?" },
      { day: 10, passage: "Ecclesiastes 5:10-12", theme: "The Hunger of More", prompt: "What purchase are you hoping will solve something money cannot touch?" },
      { day: 11, passage: "Proverbs 22:7", theme: "Debt and Bondage", prompt: "Where has borrowed living started stealing your peace?" },
      { day: 12, passage: "Matthew 25:14-30", theme: "Steward the Talents", prompt: "What resource in your hands keeps getting buried out of fear?" },
      { day: 13, passage: "James 5:1-6", theme: "Wealth and Injustice", prompt: "Who pays the hidden cost for the life you want?" },
      { day: 14, passage: "Proverbs 21:5", theme: "Plans and Patience", prompt: "What financial decision would look different if you slowed down and made a real plan?" },
      { day: 15, passage: "Luke 19:1-10", theme: "Money and Repair", prompt: "Is there any money in your story that needs to be made right?" },
      { day: 16, passage: "Philippians 4:10-13", theme: "Contentment That Can Breathe", prompt: "What would contentment change about your next financial goal?" },
      { day: 17, passage: "Proverbs 30:7-9", theme: "Neither Poverty nor Riches", prompt: "What level of comfort starts making you spiritually sleepy?" },
      { day: 18, passage: "Psalm 24:1-2", theme: "It All Belongs", prompt: "If none of this is actually yours, what becomes less stressful?" },
      { day: 19, passage: "1 John 3:16-18", theme: "Love in Deed", prompt: "Who around you has a real need you could actually meet?" },
      { day: 20, passage: "Luke 14:28-33", theme: "Count the Cost", prompt: "What future are you funding right now with your habits?" },
      { day: 21, passage: "2 Corinthians 8:1-9", theme: "The Grace of Generosity", prompt: "What would kingdom economics look like in your house, not just in your ideals?" },
    ],
  },
  health: {
    slug: "health",
    title: "Health & The Body: Honoring the Temple",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Your body is not an inconvenience to your spiritual life. Fourteen days on honoring the temple through discipline, rest, nourishment, and wise limits.",
    metaDescription:
      "Fourteen days on honoring your body as God's temple through discipline, rest, nourishment, and wise rhythms.",
    heroAlt: "Health & The Body: Honoring the Temple",
    ctaLabel: "Health & The Body",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Practice", value: "Daily rhythms" },
      { label: "Focus", value: "Rest and discipline" },
    ],
    body: [
      "A lot of spiritual language has taught people to ignore their bodies until they break. Scripture does not talk that way. Your body is not an afterthought. It is part of your worship, your limits, your calling, and your obedience.",
      "This journey helps reconnect spiritual formation and physical life: sleep, food, movement, rest, self-control, and the kind of gentler discipline that actually lasts. Zoe will keep translating big ideas into small embodied choices you can make this week.",
    ],
    days: [
      { day: 1, passage: "1 Corinthians 6:19-20", theme: "A Borrowed Body", prompt: "If your body is a temple and not a machine, what have you been doing to it lately?" },
      { day: 2, passage: "Psalm 139:13-16", theme: "Wonderfully Made", prompt: "What part of your body do you struggle to receive with gratitude?" },
      { day: 3, passage: "Mark 1:35-39", theme: "Rhythms Before Demands", prompt: "What happens when your output outruns your quiet?" },
      { day: 4, passage: "1 Kings 19:1-8", theme: "Sleep, Bread, Water", prompt: "Maybe the most spiritual thing you need is a nap and a meal. What have you been ignoring?" },
      { day: 5, passage: "1 Timothy 4:7-8", theme: "Train for Godliness", prompt: "Where would a little discipline change a lot?" },
      { day: 6, passage: "Genesis 2:2-3", theme: "Rest as Trust", prompt: "What do you fear would happen if you actually rested?" },
      { day: 7, passage: "Daniel 1:8-16", theme: "Small Choices, Stronger Life", prompt: "Which daily habit is quietly shaping who you are becoming?" },
      { day: 8, passage: "Proverbs 4:20-27", theme: "Guard Your Gates", prompt: "What are you feeding your body and mind that leaves you foggy or thin?" },
      { day: 9, passage: "Romans 12:1", theme: "Embodied Worship", prompt: "How can your sleep, food, movement, and limits become worship instead of self-improvement theater?" },
      { day: 10, passage: "Matthew 11:28-30", theme: "The Light Yoke", prompt: "Where does your pace prove you think everything depends on you?" },
      { day: 11, passage: "3 John 1:2", theme: "Whole-Person Flourishing", prompt: "When your soul is off, how does your body tell on you?" },
      { day: 12, passage: "1 Corinthians 9:24-27", theme: "Training With Purpose", prompt: "What are you saying yes to that requires a real no somewhere else?" },
      { day: 13, passage: "Psalm 23:1-3", theme: "What Restores You", prompt: "What genuinely restores you instead of just numbing you for a while?" },
      { day: 14, passage: "Galatians 5:22-23", theme: "Gentle Self-Control", prompt: "What would a gentler kind of discipline look like this week?" },
    ],
  },
  "fear-anxiety": {
    slug: "fear-anxiety",
    title: "Fear & Anxiety: From Worry to Trust",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Fear can run your life quietly or loudly. Fourteen days on naming worry honestly and learning a slower, sturdier trust in God.",
    metaDescription:
      "Fourteen days on replacing worry with trust, naming fear honestly, and practicing peace under pressure.",
    heroAlt: "Fear & Anxiety: From Worry to Trust",
    ctaLabel: "Fear & Anxiety",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Practice", value: "Honest prayer" },
      { label: "Focus", value: "Trust over worry" },
    ],
    body: [
      "Anxiety rarely introduces itself politely. It comes through spinning thoughts, control, irritability, numbness, catastrophizing, or the deep sense that if you stop bracing, everything will fall apart. Scripture does not shame fear. It keeps inviting you to bring it into the open.",
      "This journey does not promise a quick emotional hack. It is a slower move from panic toward trust. Zoe will help you name what you fear, pray concretely, and practice the kind of peace that grows through honesty, not denial.",
    ],
    days: [
      { day: 1, passage: "Matthew 6:25-34", theme: "Tomorrow Is Loud", prompt: "What sentence has anxiety been repeating in your head lately?" },
      { day: 2, passage: "Psalm 56:3-4", theme: "Name the Fear", prompt: "What happens when you stop calling it stress and say what you are actually afraid of?" },
      { day: 3, passage: "Philippians 4:4-9", theme: "Specific Prayer", prompt: "Try swapping vague panic for specific prayer. What exactly are you handing over?" },
      { day: 4, passage: "Isaiah 41:10", theme: "Not Alone in This", prompt: "Where have you been acting abandoned?" },
      { day: 5, passage: "Mark 4:35-41", theme: "Storms and Small Faith", prompt: "What makes you feel like Jesus is asleep in your boat?" },
      { day: 6, passage: "Luke 12:6-7", theme: "Seen in the Details", prompt: "What if your life is not fragile to God, even if it feels fragile to you?" },
      { day: 7, passage: "Psalm 27:1-3", theme: "Whom Shall I Fear", prompt: "What threat feels bigger than God today?" },
      { day: 8, passage: "1 Peter 5:6-7", theme: "Throw the Weight", prompt: "What do you keep carrying because control feels safer than trust?" },
      { day: 9, passage: "2 Timothy 1:7", theme: "Power, Love, Sound Mind", prompt: "Which counterfeit has been running the room: panic, avoidance, or anger?" },
      { day: 10, passage: "Psalm 46:1-3", theme: "Refuge Is Real", prompt: "What would change this afternoon if refuge was real and not just a word?" },
      { day: 11, passage: "John 14:1-6", theme: "Troubled Hearts", prompt: "What grief or uncertainty keeps hijacking your peace?" },
      { day: 12, passage: "Romans 8:31-39", theme: "Nothing Can Separate", prompt: "Which worst-case scenario do you believe could finally put you beyond God's reach?" },
      { day: 13, passage: "Exodus 14:10-14", theme: "Stand Still", prompt: "Where does your fear make you frantic instead of faithful?" },
      { day: 14, passage: "Psalm 131:1-3", theme: "A Quieted Soul", prompt: "Take five slow minutes today. Can you let your soul stop performing adulthood for a moment?" },
    ],
  },
  marriage: {
    slug: "marriage",
    title: "Marriage: Covenant & Closeness",
    duration: "21 Days",
    difficulty: "intermediate",
    description:
      "Marriage drifts when closeness gets replaced by logistics. Twenty-one days on covenant, conflict, intimacy, repair, and staying tender on purpose.",
    metaDescription:
      "Twenty-one days on covenant, conflict, intimacy, tenderness, and staying close in marriage.",
    heroAlt: "Marriage: Covenant & Closeness",
    ctaLabel: "Marriage",
    stats: [
      { label: "Duration", value: "21 Days" },
      { label: "Check-ins", value: "3 per day" },
      { label: "Focus", value: "Covenant and repair" },
    ],
    body: [
      "Marriage does not usually fall apart in one dramatic moment. More often it thins out slowly. Conversations become logistical. Irritations calcify. Intimacy gets postponed. Tenderness gets crowded out. Scripture speaks to marriage as covenant, friendship, service, delight, and steady repair.",
      "This journey is for the quiet drift as much as the obvious conflict. Zoe will keep asking about tone, patterns, pride, pursuit, apology, and the kind of ordinary intentionality that keeps a marriage alive instead of merely functioning.",
    ],
    days: [
      { day: 1, passage: "Genesis 2:18-25", theme: "More Than Roommates", prompt: "Where has closeness in your marriage quietly turned into logistics?" },
      { day: 2, passage: "Ephesians 5:21", theme: "Mutual Submission", prompt: "What would it look like to outdo each other in humility instead of winning?" },
      { day: 3, passage: "Song of Songs 8:6-7", theme: "Fierce and Tender", prompt: "What keeps your love warm instead of merely functional?" },
      { day: 4, passage: "Colossians 3:12-14", theme: "What Version of You Shows Up", prompt: "Which version of you keeps showing up in your marriage: gentle or exhausted?" },
      { day: 5, passage: "James 1:19-20", theme: "Slow Down the Fight", prompt: "What argument in your marriage actually starts with not feeling heard?" },
      { day: 6, passage: "Proverbs 18:21", theme: "Life and Death in the Mouth", prompt: "What phrase from you lands like acid on your spouse?" },
      { day: 7, passage: "1 Corinthians 13:4-7", theme: "Love Under Pressure", prompt: "Which line in this passage sounds beautiful until your spouse disappoints you?" },
      { day: 8, passage: "Ecclesiastes 4:9-12", theme: "Carry It Together", prompt: "Where are you trying to carry life solo while technically married?" },
      { day: 9, passage: "Matthew 7:3-5", theme: "The Log in the Living Room", prompt: "What do you criticize in them because it is easier than facing it in you?" },
      { day: 10, passage: "1 Peter 3:7", theme: "Understanding and Honor", prompt: "How well do you actually know what it is like to be married to you?" },
      { day: 11, passage: "Philippians 2:1-4", theme: "Consider the Other", prompt: "What need of your spouse have you minimized because yours feels louder?" },
      { day: 12, passage: "Mark 10:2-12", theme: "Covenant Before Mood", prompt: "What keeps you anchored when the feelings are thin?" },
      { day: 13, passage: "Proverbs 5:18-19", theme: "Delight Again", prompt: "What helps delight return when duty has taken over?" },
      { day: 14, passage: "Genesis 29:20", theme: "Love That Shows Up", prompt: "What small act of effort would make your spouse feel chosen this week?" },
      { day: 15, passage: "Ephesians 4:26-32", theme: "Repair Quickly", prompt: "What apology have you delayed because you want them to go first?" },
      { day: 16, passage: "Romans 12:18", theme: "Own Your Part", prompt: "What part of repair is actually yours, even if they are not ready yet?" },
      { day: 17, passage: "1 Thessalonians 5:11", theme: "Build Up Your Person", prompt: "When was the last time your spouse felt strengthened by you?" },
      { day: 18, passage: "Psalm 127:1", theme: "Unless the Lord Builds", prompt: "Where do you need God in your marriage, not just better communication?" },
      { day: 19, passage: "1 Corinthians 7:3-5", theme: "Honoring Desire", prompt: "What conversation about intimacy have you avoided because honesty feels vulnerable?" },
      { day: 20, passage: "Hosea 2:14-16", theme: "Speak Tenderly", prompt: "What would tenderness sound like in the place where you have both gotten sharp?" },
      { day: 21, passage: "John 2:1-11", theme: "Invite Jesus Back In", prompt: "Bring Jesus into the ordinary jars of your marriage. What needs his touch?" },
    ],
  },
  parenting: {
    slug: "parenting",
    title: "Parenting: Raising Humans on Purpose",
    duration: "21 Days",
    difficulty: "intermediate",
    description:
      "Parenting can feel equal parts holy and exhausting. Twenty-one days on raising kids with intention, grace, boundaries, and a calmer soul.",
    metaDescription:
      "Twenty-one days on parenting with intention, grace, discipline, gentleness, and trust in God.",
    heroAlt: "Parenting: Raising Humans on Purpose",
    ctaLabel: "Parenting",
    stats: [
      { label: "Duration", value: "21 Days" },
      { label: "Check-ins", value: "3 per day" },
      { label: "Focus", value: "Grace and guidance" },
    ],
    body: [
      "Parenting exposes you fast. Your patience, your fears, your control, your wounds, your tenderness, your limits, all of it shows up in the room. Scripture treats children as gifts, not property, and parents as stewards, not saviors.",
      "This journey is about formation for both you and your kids. Zoe will help you think about atmosphere, correction, gentleness, consistency, family rhythms, storytelling, release, and what it means to shepherd the actual child in front of you rather than the one in your head.",
    ],
    days: [
      { day: 1, passage: "Psalm 127:3-5", theme: "Stewarding, Not Owning", prompt: "Where are you treating your child like a project instead of a person?" },
      { day: 2, passage: "Deuteronomy 6:4-9", theme: "Discipleship at Home", prompt: "What are your kids learning from your atmosphere, not your speeches?" },
      { day: 3, passage: "Ephesians 6:4", theme: "Do Not Exasperate", prompt: "What tone from you makes the room tighten?" },
      { day: 4, passage: "Proverbs 22:6", theme: "Train the Bent, Not a Script", prompt: "Are you trying to raise a clone or learn your actual child?" },
      { day: 5, passage: "Mark 10:13-16", theme: "Jesus and Children", prompt: "Do your kids feel welcomed by you when they are inconvenient?" },
      { day: 6, passage: "James 1:19-20", theme: "Slow Parent, Strong Parent", prompt: "What usually happens right before you lose patience?" },
      { day: 7, passage: "Luke 15:11-24", theme: "Grace and Consequences", prompt: "What does grace look like without pretending consequences are not real?" },
      { day: 8, passage: "Colossians 3:21", theme: "Do Not Crush Their Heart", prompt: "How can correction leave dignity intact?" },
      { day: 9, passage: "1 Samuel 1:27-28", theme: "Released to God", prompt: "What fear makes you hold your child too tightly?" },
      { day: 10, passage: "Proverbs 15:1", theme: "Soft Answers", prompt: "What conflict in your home would change if your volume dropped first?" },
      { day: 11, passage: "Psalm 78:4-7", theme: "Tell the Story", prompt: "What God-story from your life do your kids need to hear from you?" },
      { day: 12, passage: "Galatians 6:9", theme: "Ordinary Faithfulness", prompt: "What hidden parent work feels thankless right now?" },
      { day: 13, passage: "Luke 2:41-52", theme: "Let Them Grow", prompt: "Where do you need to stop scripting and start shepherding?" },
      { day: 14, passage: "Philippians 4:5", theme: "Obvious Gentleness", prompt: "Would your child describe you as safe?" },
      { day: 15, passage: "Hebrews 12:5-11", theme: "Discipline That Loves", prompt: "Is your correction about their formation or your irritation?" },
      { day: 16, passage: "Proverbs 3:5-6", theme: "Trusting God With Their Future", prompt: "Which fear about your child's future keeps stealing today's peace?" },
      { day: 17, passage: "3 John 1:4", theme: "What Success Really Is", prompt: "What version of success matters most for your child, really?" },
      { day: 18, passage: "Exodus 18:17-23", theme: "Parenting Needs Community", prompt: "Who helps carry your family so you do not burn out?" },
      { day: 19, passage: "Matthew 6:33", theme: "Seek First at Home", prompt: "What family rhythm would make God feel central instead of squeezed in?" },
      { day: 20, passage: "2 Timothy 1:5", theme: "Faith Across Generations", prompt: "What faith did you inherit, and what are you passing on?" },
      { day: 21, passage: "John 21:15", theme: "Feed My Lambs", prompt: "How might love for Jesus change the way you parent today?" },
    ],
  },
  purpose: {
    slug: "purpose",
    title: "Purpose & Calling: Your Assignment",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Calling usually gets discovered in faithfulness, not fantasy. Fourteen days on finding your assignment and living it without comparing your path to somebody else's.",
    metaDescription:
      "Fourteen days on purpose, calling, gifts, faithfulness, and learning to live your actual assignment.",
    heroAlt: "Purpose & Calling: Your Assignment",
    ctaLabel: "Purpose & Calling",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Calling and gifts" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Purpose can become one more place to chase an impressive life. Scripture talks about calling differently. It is often slower, more local, more relational, and more faithful than the version we imagine. Calling is not just what you do. It is how you carry who you are into the places God has given you.",
      "This journey helps name gifts, burdens, opportunities, and the specific good works prepared for you. Zoe will keep cutting through comparison and vague ambition so you can pay attention to what is already in front of you.",
    ],
    days: [
      { day: 1, passage: "Ephesians 2:10", theme: "Made on Purpose", prompt: "Where do you keep acting accidental?" },
      { day: 2, passage: "Jeremiah 1:4-8", theme: "Known Before Visible", prompt: "What calling feels too big because you keep staring at your limits?" },
      { day: 3, passage: "Exodus 3:1-12", theme: "Holy Interruptions", prompt: "What burning bush moment have you been brushing off because it is inconvenient?" },
      { day: 4, passage: "Psalm 139:13-18", theme: "Intentional Design", prompt: "What strengths or burdens in you feel repeated enough to pay attention to?" },
      { day: 5, passage: "Matthew 5:13-16", theme: "Salt Somewhere Specific", prompt: "Who are you supposed to serve right where you already are?" },
      { day: 6, passage: "Romans 12:4-8", theme: "Different Gifts, Same Body", prompt: "What grace comes naturally to you that you keep treating as ordinary?" },
      { day: 7, passage: "John 15:1-8", theme: "Fruit, Not Frenzy", prompt: "What are you forcing that might grow better from abiding?" },
      { day: 8, passage: "Esther 4:13-16", theme: "For This Moment", prompt: "Where might your current season be less random than it feels?" },
      { day: 9, passage: "Philippians 3:12-14", theme: "Press On", prompt: "What good thing did you drop because it took longer than your ego liked?" },
      { day: 10, passage: "Acts 13:1-3", theme: "Calling in Community", prompt: "Who knows you well enough to help name your calling?" },
      { day: 11, passage: "Colossians 3:17", theme: "Whatever You Do", prompt: "What if purpose is smaller and more faithful than your fantasy?" },
      { day: 12, passage: "2 Timothy 1:6-7", theme: "Fan Into Flame", prompt: "What gift in you has gone cold from neglect or fear?" },
      { day: 13, passage: "Micah 6:8", theme: "The Assignment in Plain Language", prompt: "What part of justice, mercy, or humility is most clearly yours right now?" },
      { day: 14, passage: "John 21:20-22", theme: "Walk Your Own Path", prompt: "Whose path are you obsessing over instead of walking your own?" },
    ],
  },
  identity: {
    slug: "identity",
    title: "Identity: Who God Made You to Be",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Most people live from a stack of roles, wounds, and performance metrics. Fourteen days on receiving your truest identity in God and letting false selves lose their grip.",
    metaDescription:
      "Fourteen days on belovedness, adoption, truth, and learning to live from who God says you are.",
    heroAlt: "Identity: Who God Made You to Be",
    ctaLabel: "Identity",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "True self" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Identity confusion does not always look dramatic. Sometimes it looks productive. Sometimes it looks religious. Sometimes it looks like trying very hard to be impressive, needed, desirable, in control, or impossible to reject. Scripture keeps bringing you back underneath all of that.",
      "This journey walks through image-bearing, belovedness, adoption, truth, and the freedom of being hidden with Christ. Zoe will keep asking where you still live like an orphan, employee, performer, or fraud instead of a loved child of God.",
    ],
    days: [
      { day: 1, passage: "Genesis 1:26-27", theme: "Image-Bearer", prompt: "Before you achieve anything today, who are you?" },
      { day: 2, passage: "Matthew 3:16-17", theme: "Beloved Before Performance", prompt: "Jesus heard beloved before ministry. What do you keep trying to earn?" },
      { day: 3, passage: "Psalm 139:1-6", theme: "Known All the Way Down", prompt: "What part of yourself do you assume God merely tolerates?" },
      { day: 4, passage: "John 15:15", theme: "Friends, Not Employees", prompt: "If you stopped relating to God like a boss, what would change?" },
      { day: 5, passage: "Romans 8:14-17", theme: "Spirit of Adoption", prompt: "Where does orphan energy still run your life?" },
      { day: 6, passage: "2 Corinthians 5:17", theme: "New Creation", prompt: "What old label keeps surviving longer than it should?" },
      { day: 7, passage: "Colossians 3:1-4", theme: "Hidden With Christ", prompt: "What are you using to prove you matter?" },
      { day: 8, passage: "Ephesians 1:3-8", theme: "Chosen and Wanted", prompt: "Which word is hardest to believe about yourself: chosen, holy, forgiven, loved?" },
      { day: 9, passage: "Luke 15:1-7", theme: "The One He Comes After", prompt: "What part of you feels too lost to be pursued?" },
      { day: 10, passage: "Galatians 2:20", theme: "Christ Lives in Me", prompt: "If Christ is alive in you, what false story loses power?" },
      { day: 11, passage: "1 Peter 2:9", theme: "A New Name and a New People", prompt: "Who are you when you stop introducing yourself by wounds and roles?" },
      { day: 12, passage: "John 8:31-36", theme: "Truth That Frees", prompt: "What lie about yourself still gets treated like fact?" },
      { day: 13, passage: "Philippians 3:7-9", theme: "Losing the Costume", prompt: "What identity marker would be hardest for you to count as loss?" },
      { day: 14, passage: "1 John 3:1-3", theme: "Children of God", prompt: "Sit with this without rushing: you are God's child. What rises up in you when you hear that?" },
    ],
  },
  forgiveness: {
    slug: "forgiveness",
    title: "Forgiveness: The Art of Letting Go",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Forgiveness is not pretending the wound was small. Fourteen days on releasing others, receiving mercy yourself, and refusing to let bitterness become your identity.",
    metaDescription:
      "Fourteen days on forgiveness, releasing bitterness, receiving mercy, and learning to let go without minimizing harm.",
    heroAlt: "Forgiveness: The Art of Letting Go",
    ctaLabel: "Forgiveness",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Mercy and release" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Forgiveness is one of the most misunderstood commands in the Christian life. It is not amnesia. It is not calling evil good. It is not instant trust. It is the costly work of releasing vengeance, refusing bitterness, and opening your clenched hands to the mercy you yourself live on.",
      "This journey moves through wounds, confession, mercy, repair, resentment, and self-forgiveness. Zoe will not rush you, but it will keep asking whether pain has quietly become a place you live instead of a place you have walked through.",
    ],
    days: [
      { day: 1, passage: "Matthew 18:21-35", theme: "The Debt We Forget", prompt: "Who do you keep billing in your heart?" },
      { day: 2, passage: "Ephesians 4:31-32", theme: "Put Down the Knife", prompt: "What bitterness still feels justified to you?" },
      { day: 3, passage: "Psalm 32:1-5", theme: "Start With Your Own Need", prompt: "Where do you need mercy before you can offer it?" },
      { day: 4, passage: "Luke 23:32-34", theme: "Forgiveness Under Wound", prompt: "What changes when forgiveness stops waiting for an apology?" },
      { day: 5, passage: "Colossians 3:12-13", theme: "Make Room to Release", prompt: "Who still lives rent-free in your nervous system?" },
      { day: 6, passage: "Genesis 50:15-21", theme: "Joseph and the Long Road", prompt: "What evil done to you are you afraid forgiveness will minimize?" },
      { day: 7, passage: "Romans 12:17-21", theme: "No Payback Fantasy", prompt: "How do you try to win back power when you have been hurt?" },
      { day: 8, passage: "Mark 2:1-12", theme: "Forgiven People Walk Different", prompt: "What shame are you still dragging after Jesus has already spoken?" },
      { day: 9, passage: "Psalm 51:1-12", theme: "Mercy for the One in the Mirror", prompt: "What do you need to forgive yourself for without calling evil good?" },
      { day: 10, passage: "Luke 7:36-50", theme: "Love After Mercy", prompt: "How has being forgiven changed your capacity to love?" },
      { day: 11, passage: "2 Corinthians 2:5-11", theme: "Do Not Let Bitterness Finish the Job", prompt: "What unresolved wound is quietly hardening you?" },
      { day: 12, passage: "Matthew 5:23-24", theme: "Move Toward Repair", prompt: "Is there a conversation you have delayed because you would rather be right than free?" },
      { day: 13, passage: "Hebrews 12:14-15", theme: "Root Systems", prompt: "What small resentment is growing roots because you keep feeding it?" },
      { day: 14, passage: "John 21:15-19", theme: "Restored After Failure", prompt: "If Jesus restores people after collapse, what future might still be available to you?" },
    ],
  },
  prayer: {
    slug: "prayer",
    title: "Prayer: Learning to Listen",
    duration: "21 Days",
    difficulty: "introductory",
    description:
      "Prayer is more than sending requests upward. Twenty-one days on talking to God honestly, listening well, and building a life that makes room for his voice.",
    metaDescription:
      "Twenty-one days on prayer, listening, intercession, honesty, and learning to speak with God in a real relationship.",
    heroAlt: "Prayer: Learning to Listen",
    ctaLabel: "Prayer",
    stats: [
      { label: "Duration", value: "21 Days" },
      { label: "Practice", value: "Daily prayer" },
      { label: "Focus", value: "Listening and honesty" },
    ],
    body: [
      "A lot of people feel guilty about prayer because they think they are bad at it. Usually the problem is not ability. It is imagination. Prayer is not performance. It is relationship. It is honesty, attention, persistence, surrender, and the slow learning of God's voice.",
      "This journey moves from simple conversation to listening, intercession, dangerous prayers, and surrender. Zoe will help prayer feel less like religious homework and more like a real place where your actual life meets God.",
    ],
    days: [
      { day: 1, passage: "Matthew 6:5-8", theme: "Honest Over Impressive", prompt: "When you pray, who are you trying to sound like?" },
      { day: 2, passage: "Luke 11:1-4", theme: "Teach Us to Pray", prompt: "Which line of the Lord's Prayer feels most alive to you right now?" },
      { day: 3, passage: "Psalm 62:8", theme: "Pour Out Your Heart", prompt: "What have you been editing out of prayer?" },
      { day: 4, passage: "Mark 1:35-39", theme: "Make a Place", prompt: "Where could prayer actually fit if you stopped waiting for ideal conditions?" },
      { day: 5, passage: "Romans 8:26-27", theme: "When Words Run Out", prompt: "What if your inability to pray well is not a barrier after all?" },
      { day: 6, passage: "John 15:7-8", theme: "Ask From Abiding", prompt: "How would your prayers change if closeness mattered more than outcome?" },
      { day: 7, passage: "Philippians 4:6-7", theme: "Turn the Fear Into a Prayer", prompt: "Take one spinning fear and rewrite it as one concrete prayer." },
      { day: 8, passage: "Psalm 27:4", theme: "One Thing", prompt: "What do you want from God once the religious answers are stripped away?" },
      { day: 9, passage: "Luke 18:1-8", theme: "Keep Knocking", prompt: "What request have you stopped bringing because disappointment got there first?" },
      { day: 10, passage: "1 Samuel 3:1-10", theme: "Speak, Lord", prompt: "If God interrupted your day, would you notice?" },
      { day: 11, passage: "Nehemiah 1:4-11", theme: "Prayer That Moves Into Action", prompt: "What burden keeps moving from your chest into your prayers?" },
      { day: 12, passage: "Exodus 33:12-18", theme: "Show Me Your Glory", prompt: "Are you asking God for help or for himself?" },
      { day: 13, passage: "James 5:13-18", theme: "Pray in Every Weather", prompt: "What emotion do you rarely bring to God: joy, grief, anger, gratitude?" },
      { day: 14, passage: "Psalm 139:23-24", theme: "The Dangerous Prayer", prompt: "What would you rather God not expose in you?" },
      { day: 15, passage: "John 17:20-23", theme: "Praying Beyond Yourself", prompt: "Who needs your intercession more than your opinion?" },
      { day: 16, passage: "Habakkuk 2:1", theme: "Wait for the Reply", prompt: "Can you sit long enough after praying to listen?" },
      { day: 17, passage: "Colossians 4:2", theme: "Watchful Prayer", prompt: "Where has prayer become rushed and sleepy?" },
      { day: 18, passage: "Acts 4:23-31", theme: "Bold Requests", prompt: "What are you afraid to ask because it would require courage if God answered?" },
      { day: 19, passage: "Matthew 26:36-44", theme: "Not My Will", prompt: "What prayer are you resisting because surrender would cost you something?" },
      { day: 20, passage: "Psalm 84:1-4", theme: "Desire as Prayer", prompt: "What longing in you might actually be a prayer?" },
      { day: 21, passage: "John 11:41-42", theme: "Pray Like You Are Heard", prompt: "How would you pray today if you were certain God was listening?" },
    ],
  },
  "faith-doubt": {
    slug: "faith-doubt",
    title: "Faith & Doubt: Honest Questions",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Faith is not the absence of questions. Fourteen days on bringing your doubts into the light and learning a more honest, resilient trust in God.",
    metaDescription:
      "Fourteen days on honest questions, doubt, trust, and building real belief without pretending certainty.",
    heroAlt: "Faith & Doubt: Honest Questions",
    ctaLabel: "Faith & Doubt",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Honest belief" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Many people think doubt is what happens when faith starts failing. Scripture often treats doubt as the place where faith gets honest enough to grow. Questions do not scare God. Pretense does. There is a way of doubting that keeps you moving toward Jesus instead of away from him.",
      "This journey makes room for unresolved tension, disappointment, confusion, and the strange coexistence of faith and unbelief. Zoe will not rush you to easy answers, but it will keep you company as trust gets rebuilt on something sturdier than performance.",
    ],
    days: [
      { day: 1, passage: "Mark 9:14-29", theme: "Help My Unbelief", prompt: "What do you believe and not believe at the same time?" },
      { day: 2, passage: "Psalm 73:1-17", theme: "When Faith Feels Unfair", prompt: "What part of someone else's story makes trusting God harder for you?" },
      { day: 3, passage: "John 20:24-29", theme: "Wounds and Questions", prompt: "What evidence do you keep asking God for?" },
      { day: 4, passage: "Habakkuk 1:1-4", theme: "Faith That Complains Honestly", prompt: "What accusation against God have you only said privately?" },
      { day: 5, passage: "Luke 7:18-23", theme: "Are You Really the One", prompt: "Where has disappointment made you suspicious of Jesus?" },
      { day: 6, passage: "Hebrews 11:1-6", theme: "Trust Without Full Visibility", prompt: "What step of faith are you delaying until certainty arrives?" },
      { day: 7, passage: "Psalm 13", theme: "How Long Can Coexist With Trust", prompt: "Can you complain to God without walking away from him?" },
      { day: 8, passage: "Jude 20-22", theme: "Mercy for the Doubter", prompt: "How do you treat the doubtful parts of yourself?" },
      { day: 9, passage: "John 6:60-69", theme: "Hard Teachings", prompt: "What teaching of Jesus makes you want to back away?" },
      { day: 10, passage: "Genesis 15:1-6", theme: "Counting Stars in the Dark", prompt: "What promise feels laughably far from your current reality?" },
      { day: 11, passage: "2 Timothy 2:11-13", theme: "He Remains Faithful", prompt: "Where are you more aware of your inconsistency than God's?" },
      { day: 12, passage: "Psalm 77:1-12", theme: "Remembering in the Night", prompt: "What past faithfulness of God do you need to drag into the present?" },
      { day: 13, passage: "Romans 10:14-17", theme: "Feed Faith Intentionally", prompt: "What voices are feeding your doubts more than Scripture is feeding your faith?" },
      { day: 14, passage: "Hebrews 12:1-2", theme: "Keep Walking", prompt: "What would it look like to keep walking without pretending all your questions are gone?" },
    ],
  },
  "work-ambition": {
    slug: "work-ambition",
    title: "Work & Ambition: Grinding Without Losing Your Soul",
    duration: "14 Days",
    difficulty: "intermediate",
    description:
      "Work can become worship, avoidance, service, or addiction. Fourteen days on ambition, vocation, hustle, rest, and staying spiritually awake while you build.",
    metaDescription:
      "Fourteen days on work, ambition, vocation, rest, and building without losing your soul.",
    heroAlt: "Work & Ambition: Grinding Without Losing Your Soul",
    ctaLabel: "Work & Ambition",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Work and vocation" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Work is a gift. Work is also one of the easiest places to hide from yourself. Ambition can become stewardship or self-salvation. A full calendar can mean calling or compulsion. Scripture gives a better vision: excellent work offered to God, free from the need to prove your worth through it.",
      "This journey helps sort clean ambition from ego, calling from compulsion, diligence from drivenness. Zoe will keep asking who you are working for, what work is doing to you, and whether success is costing more than you realize.",
    ],
    days: [
      { day: 1, passage: "Colossians 3:23-24", theme: "The Right Audience", prompt: "Who are you really working for right now?" },
      { day: 2, passage: "Genesis 2:15", theme: "Work Before the Fall", prompt: "What part of work still feels like calling instead of grind?" },
      { day: 3, passage: "Matthew 11:28-30", theme: "Ambition Under a Lighter Yoke", prompt: "Where has striving become your personality?" },
      { day: 4, passage: "Proverbs 16:3", theme: "Commit the Work", prompt: "What project are you gripping harder than you need to?" },
      { day: 5, passage: "Luke 10:38-42", theme: "Doing Versus Being", prompt: "What is your inner Martha trying to prove?" },
      { day: 6, passage: "Ecclesiastes 4:4-8", theme: "Hustle and Envy", prompt: "How much of your drive is clean, and how much is comparison?" },
      { day: 7, passage: "Psalm 90:17", theme: "Established Work", prompt: "What would fruitfulness look like if it were not measured by applause?" },
      { day: 8, passage: "Daniel 6:3-5", theme: "Excellence Without Compromise", prompt: "Where are you tempted to bend because everybody else does?" },
      { day: 9, passage: "Mark 8:34-37", theme: "Gain and Loss", prompt: "What career win could cost you too much?" },
      { day: 10, passage: "Proverbs 23:4-5", theme: "Stop Wearing Yourself Out", prompt: "Where are you exhausted from chasing something that will not stay?" },
      { day: 11, passage: "James 4:13-16", theme: "Plans With Open Hands", prompt: "What future are you talking about as if you are in charge of it?" },
      { day: 12, passage: "1 Thessalonians 4:11-12", theme: "Quiet Faithfulness", prompt: "What if ordinary, steady work is holier than you think?" },
      { day: 13, passage: "Matthew 25:21", theme: "Faithful With What Is Yours", prompt: "What assignment have you despised because it feels small?" },
      { day: 14, passage: "John 15:4-5", theme: "Abide, Then Build", prompt: "If work flowed from union with God instead of anxiety, what would change first?" },
    ],
  },
  grief: {
    slug: "grief",
    title: "Grief & Loss: Walking Through Pain",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Grief does not get healed by pretending you are okay. Fourteen days on loss, lament, hope, and learning to carry pain without letting it freeze your life.",
    metaDescription:
      "Fourteen days on grief, lament, loss, hope, and processing pain without getting stuck.",
    heroAlt: "Grief & Loss: Walking Through Pain",
    ctaLabel: "Grief & Loss",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Lament and hope" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Grief rearranges the inside of a person. It changes time, memory, energy, and the way ordinary moments land. Scripture makes surprising room for that. It does not demand quick closure. It teaches lament, tears, waiting, and hope sturdy enough to coexist with pain.",
      "This journey is not about getting over loss. It is about walking through it with God and with enough honesty to stay human. Zoe will help you name sorrow, resist numbness, and notice how hope can be real without becoming denial.",
    ],
    days: [
      { day: 1, passage: "Psalm 34:18", theme: "Close to the Brokenhearted", prompt: "What hurt do you keep calling fine because naming it would make it real?" },
      { day: 2, passage: "John 11:32-36", theme: "Jesus Wept", prompt: "What does it mean that Jesus cried even though he knew resurrection was coming?" },
      { day: 3, passage: "Lamentations 3:17-26", theme: "Hope From the Ground", prompt: "What has grief taken from your sense of stability?" },
      { day: 4, passage: "Psalm 13", theme: "How Long", prompt: "What unanswered ache has stretched time for you?" },
      { day: 5, passage: "Matthew 5:4", theme: "Blessed Are Those Who Mourn", prompt: "Where do you need permission to mourn without rushing to silver linings?" },
      { day: 6, passage: "2 Samuel 12:15-23", theme: "Grief Changes Shape", prompt: "How has your grief changed form over time?" },
      { day: 7, passage: "Psalm 42", theme: "When Sadness Returns", prompt: "When heaviness comes back again, what story do you tell yourself about it?" },
      { day: 8, passage: "Romans 8:18-28", theme: "Groaning With Hope", prompt: "What hope feels safe enough to hold without denying the pain?" },
      { day: 9, passage: "Ecclesiastes 3:1-8", theme: "A Time to Weep", prompt: "What are you trying to force out of season?" },
      { day: 10, passage: "Isaiah 43:1-3", theme: "Through the Waters", prompt: "What does with you mean when the loss is not removed?" },
      { day: 11, passage: "1 Thessalonians 4:13-18", theme: "Grieving With Hope", prompt: "What is the difference between hope and pretending for you right now?" },
      { day: 12, passage: "Psalm 147:3", theme: "Bound Up Slowly", prompt: "Where do you still feel tender to the touch?" },
      { day: 13, passage: "Revelation 21:1-5", theme: "The End of Tears", prompt: "What future promise of God do you need because today is heavy?" },
      { day: 14, passage: "Luke 24:13-35", theme: "Companion on the Road", prompt: "Where might Jesus be walking beside you in a grief you thought you had to carry alone?" },
    ],
  },
  friendship: {
    slug: "friendship",
    title: "Friendship & Community: Iron Sharpening Iron",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Deep friendship does not happen by accident. Fourteen days on community, honesty, loyalty, confession, and building relationships that can actually hold your life.",
    metaDescription:
      "Fourteen days on friendship, community, honesty, support, and building deep relationships.",
    heroAlt: "Friendship & Community: Iron Sharpening Iron",
    ctaLabel: "Friendship & Community",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Community and honesty" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Most adults say they want deeper community while structuring their lives in ways that make it almost impossible. Scripture sees friendship and community as part of discipleship itself. You are not meant to carry your life in isolation.",
      "This journey helps you think about presence, initiative, confession, mutual care, and the difference between being surrounded and being known. Zoe will keep asking whether you are settling for polite connection when your soul is asking for something stronger.",
    ],
    days: [
      { day: 1, passage: "Ecclesiastes 4:9-12", theme: "Not Meant to Carry Alone", prompt: "Where are you doing life like a solo act?" },
      { day: 2, passage: "Proverbs 17:17", theme: "Love That Stays", prompt: "Who has actually shown up for you when life got inconvenient?" },
      { day: 3, passage: "John 15:12-15", theme: "Friendship Like Jesus", prompt: "What makes you settle for being known lightly?" },
      { day: 4, passage: "Acts 2:42-47", theme: "Shared Life", prompt: "What would deeper community cost your schedule?" },
      { day: 5, passage: "Galatians 6:1-2", theme: "Carry Each Other", prompt: "Who needs practical help from you, not just a prayer emoji?" },
      { day: 6, passage: "James 5:16", theme: "Confession and Healing", prompt: "Who knows the real you, not the edited version?" },
      { day: 7, passage: "Ruth 1:16-18", theme: "Covenant Friendship", prompt: "Which friendship in your life deserves more intentionality?" },
      { day: 8, passage: "Proverbs 27:5-6", theme: "Faithful Wounds", prompt: "Who can tell you hard truth without losing you?" },
      { day: 9, passage: "Philippians 2:1-4", theme: "Looking to Others", prompt: "Where has friendship become quietly self-centered?" },
      { day: 10, passage: "Luke 5:17-20", theme: "Friends Who Carry", prompt: "When have you let pride keep you from being carried?" },
      { day: 11, passage: "Romans 12:9-13", theme: "Move Toward People", prompt: "Who do you need to move toward instead of waiting for them to initiate?" },
      { day: 12, passage: "1 Samuel 18:1-4", theme: "Souls Knit Together", prompt: "What kind of friendship does your soul actually need right now?" },
      { day: 13, passage: "Hebrews 10:24-25", theme: "Do Not Drift Apart", prompt: "What habit would keep your people close instead of vaguely important?" },
      { day: 14, passage: "John 13:34-35", theme: "Love That Makes the Gospel Plausible", prompt: "If outsiders watched your friendships, would they see anything different?" },
    ],
  },
  anger: {
    slug: "anger",
    title: "Anger & Conflict: Fighting Fair",
    duration: "14 Days",
    difficulty: "intermediate",
    description:
      "Anger can tell the truth or torch the room. Fourteen days on righteous anger, destructive anger, repair, confrontation, and learning to fight fair.",
    metaDescription:
      "Fourteen days on anger, conflict, repair, confrontation, and learning to fight fair.",
    heroAlt: "Anger & Conflict: Fighting Fair",
    ctaLabel: "Anger & Conflict",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Repair and restraint" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Anger is not always the enemy. Sometimes it is the right response to injustice, betrayal, or violation. But anger also lies easily. It disguises hurt, pride, fear, and contempt. Scripture gives room for anger while refusing to let it become your driver.",
      "This journey helps you notice triggers, speak truth without contempt, confront wisely, and repair what anger tends to break. Zoe will keep pushing beneath the surface to ask what your anger is protecting and whether it is helping or just burning.",
    ],
    days: [
      { day: 1, passage: "Ephesians 4:26-27", theme: "Angry, Not Owned by It", prompt: "What sits under your anger when it cools down?" },
      { day: 2, passage: "James 1:19-20", theme: "Slow and Hot", prompt: "What happens to your discernment when you get triggered?" },
      { day: 3, passage: "Mark 3:1-6", theme: "Righteous Anger", prompt: "What injustice genuinely should bother you, and what is just your ego getting bruised?" },
      { day: 4, passage: "Proverbs 15:1", theme: "Tone Starts Fires", prompt: "What tone turns a disagreement into a blaze?" },
      { day: 5, passage: "Matthew 5:21-24", theme: "Murder Starts Small", prompt: "Who are you dehumanizing in your head?" },
      { day: 6, passage: "Proverbs 29:11", theme: "Keeping the Whole Mind", prompt: "How do you leak anger before you admit it?" },
      { day: 7, passage: "Romans 12:17-21", theme: "No Payback Fantasy", prompt: "What revenge story have you been replaying?" },
      { day: 8, passage: "Colossians 3:8-14", theme: "Take Off the Old Self", prompt: "Which form of anger suits you best: sharp words, icy distance, sarcasm, withdrawal?" },
      { day: 9, passage: "Matthew 18:15-17", theme: "Go to the Person", prompt: "What conflict would improve if you stopped talking around it?" },
      { day: 10, passage: "Psalm 139:23-24", theme: "Search the Trigger", prompt: "What old wound is getting touched in this conflict?" },
      { day: 11, passage: "Galatians 6:1", theme: "Restore Gently", prompt: "Can truth come out of your mouth without contempt riding with it?" },
      { day: 12, passage: "2 Timothy 2:23-25", theme: "Not Quarrelsome", prompt: "Where do you keep picking fights that never produce fruit?" },
      { day: 13, passage: "Proverbs 19:11", theme: "Wisely Overlook", prompt: "What actually needs confrontation, and what needs release?" },
      { day: 14, passage: "Romans 14:19", theme: "Build Peace", prompt: "What would fighting fair look like in your home this week?" },
    ],
  },
  wisdom: {
    slug: "wisdom",
    title: "Wisdom & Decision-Making: The Discerning Life",
    duration: "21 Days",
    difficulty: "intermediate",
    description:
      "Discernment is more than choosing between good and bad. Twenty-one days on decisions, timing, counsel, peace, and learning how wisdom actually works.",
    metaDescription:
      "Twenty-one days on discernment, decisions, counsel, timing, and learning the wise life.",
    heroAlt: "Wisdom & Decision-Making: The Discerning Life",
    ctaLabel: "Wisdom & Decision-Making",
    stats: [
      { label: "Duration", value: "21 Days" },
      { label: "Check-ins", value: "3 per day" },
      { label: "Focus", value: "Discernment for crossroads" },
    ],
    body: [
      "Some decisions are easy because they are obviously right or obviously wrong. Most of life is not like that. Most of life is choosing between good things, uncertain futures, mixed motives, and incomplete information. Wisdom is the skill of living well with God in that kind of world.",
      "This journey helps you think about reverence, prayer, counsel, timing, obedience, peace, prudence, and the slow training of perception. Zoe will keep asking whether you are trying to get a perfect blueprint or become the kind of person who can recognize the next faithful step.",
    ],
    days: [
      { day: 1, passage: "Proverbs 1:1-7", theme: "Start With Reverence", prompt: "Is your decision-making starting with fear of God or fear of consequences?" },
      { day: 2, passage: "James 1:5", theme: "Ask Boldly for Wisdom", prompt: "What choice have you analyzed to death but barely prayed about?" },
      { day: 3, passage: "Proverbs 3:5-6", theme: "Not Leaning on Yourself", prompt: "Where do you trust your instincts more than God's leading?" },
      { day: 4, passage: "Psalm 25:4-5", theme: "Teach Me Your Paths", prompt: "What if guidance is less about a blueprint and more about walking with someone?" },
      { day: 5, passage: "1 Kings 3:5-12", theme: "A Listening Heart", prompt: "If God offered one thing for this season, would you ask for wisdom or just relief?" },
      { day: 6, passage: "Luke 6:46-49", theme: "Wisdom That Obeys", prompt: "What truth do you already know that you keep calling discernment instead of obedience?" },
      { day: 7, passage: "Ecclesiastes 3:1-8", theme: "Timing Matters", prompt: "Is the issue the decision itself, or the timing?" },
      { day: 8, passage: "Proverbs 11:14", theme: "Counsel That Keeps You Safe", prompt: "Who has earned the right to speak into this crossroads?" },
      { day: 9, passage: "Acts 15:1-21", theme: "Discernment in Community", prompt: "What happens when you stop treating major decisions like private property?" },
      { day: 10, passage: "Psalm 119:105", theme: "Enough Light for the Next Step", prompt: "What next step is actually clear, even if the ten after that are not?" },
      { day: 11, passage: "Philippians 1:9-11", theme: "Love That Knows What Is Best", prompt: "Can you tell the difference between a good option and the best one?" },
      { day: 12, passage: "1 Thessalonians 5:21-22", theme: "Test Everything", prompt: "What needs to be examined instead of just felt?" },
      { day: 13, passage: "Proverbs 16:1-3", theme: "Plans Submitted", prompt: "What plan have you built without asking whether God wants it?" },
      { day: 14, passage: "Exodus 13:17-22", theme: "The Long Way On Purpose", prompt: "Where might the slower route actually be mercy?" },
      { day: 15, passage: "Colossians 3:15", theme: "Let Peace Referee", prompt: "What choice produces deep settled peace instead of adrenaline?" },
      { day: 16, passage: "Romans 12:1-2", theme: "A Renewed Mind", prompt: "What pattern around you is distorting your judgment?" },
      { day: 17, passage: "Psalm 37:3-7", theme: "Trust, Do Good, Wait", prompt: "Which decision are you trying to force because waiting feels weak?" },
      { day: 18, passage: "Matthew 7:24-27", theme: "Build on Rock", prompt: "Will this choice still hold when pressure hits?" },
      { day: 19, passage: "Proverbs 27:12", theme: "See Trouble Coming", prompt: "What risk are you minimizing because you want the outcome?" },
      { day: 20, passage: "John 10:3-5", theme: "Learning the Shepherd's Voice", prompt: "How do you usually recognize God's leading in your actual life?" },
      { day: 21, passage: "Hebrews 12:1-2", theme: "Remember Who You Are Becoming", prompt: "What decision becomes clearer when you remember who you are becoming?" },
    ],
  },
  addiction: {
    slug: "addiction",
    title: "Addiction & Freedom: Breaking Chains",
    duration: "21 Days",
    difficulty: "deep",
    description:
      "Freedom usually starts with truth, not willpower. Twenty-one days on breaking destructive cycles, bringing hidden things into the light, and learning to live free.",
    metaDescription:
      "Twenty-one days on addiction, freedom, honesty, accountability, and breaking destructive cycles.",
    heroAlt: "Addiction & Freedom: Breaking Chains",
    ctaLabel: "Addiction & Freedom",
    stats: [
      { label: "Duration", value: "21 Days" },
      { label: "Check-ins", value: "3 per day" },
      { label: "Focus", value: "Freedom and honesty" },
    ],
    body: [
      "Addiction thrives in secrecy, shame, and the lie that you should be able to fix yourself before you ask for help. Scripture tells the truth about bondage without leaving you there. Freedom is not pretending temptation is gone. It is walking in the light, naming the chain, and learning new forms of dependence.",
      "This journey is not a substitute for counseling, recovery groups, or support. It is a companion for honest spiritual work in the middle of the fight. Zoe will help you trace triggers, expose the lie beneath the craving, and build practices of confession, accountability, and hope.",
    ],
    days: [
      { day: 1, passage: "Romans 7:15-25", theme: "Doing What I Hate", prompt: "What cycle keeps making promises it never keeps?" },
      { day: 2, passage: "John 8:31-36", theme: "Freedom for Real", prompt: "Where have you settled for managing a chain instead of breaking it?" },
      { day: 3, passage: "Psalm 51:1-12", theme: "Tell the Truth", prompt: "What happens when you stop calling it a habit and name it honestly?" },
      { day: 4, passage: "James 1:13-15", theme: "Trace the Desire", prompt: "What need or wound is your addiction trying to medicate?" },
      { day: 5, passage: "1 Corinthians 10:12-13", theme: "Early Warning Lights", prompt: "When temptation rises, what is your earliest warning sign?" },
      { day: 6, passage: "Mark 5:1-20", theme: "Jesus in the Mess", prompt: "What part of your story feels too dark to bring fully into the light?" },
      { day: 7, passage: "Proverbs 28:13", theme: "Concealment Keeps It Sick", prompt: "Who knows the truth about your struggle?" },
      { day: 8, passage: "Galatians 5:1", theme: "Stand Firm in Freedom", prompt: "What false freedom keeps pulling you back?" },
      { day: 9, passage: "Matthew 5:29-30", theme: "Cut Off the Access Point", prompt: "What access point do you need to cut off, not just pray about?" },
      { day: 10, passage: "Romans 6:11-14", theme: "A New Master", prompt: "What would it mean to stop talking like sin is in charge?" },
      { day: 11, passage: "Psalm 40:1-3", theme: "Lifted From the Pit", prompt: "Remember a rescue God has already done. What does it tell you now?" },
      { day: 12, passage: "2 Timothy 2:22", theme: "Run Toward Better Desire", prompt: "What healthy hunger can replace the destructive one?" },
      { day: 13, passage: "Hebrews 3:12-13", theme: "Daily Help", prompt: "Who can check on you before you spiral, not after?" },
      { day: 14, passage: "1 Peter 5:8-10", theme: "Sober and Watchful", prompt: "What conditions make you spiritually sleepy?" },
      { day: 15, passage: "2 Corinthians 12:7-10", theme: "Grace in Weakness", prompt: "Where do you hate needing help?" },
      { day: 16, passage: "Ephesians 5:8-14", theme: "Live in the Light", prompt: "What would openness cost you, and what might it save?" },
      { day: 17, passage: "Psalm 73:25-26", theme: "Better Than the Fix", prompt: "What are you actually craving beneath the craving?" },
      { day: 18, passage: "Colossians 3:1-10", theme: "Put Off, Put On", prompt: "What old self keeps asking for the mic?" },
      { day: 19, passage: "Luke 15:17-24", theme: "Coming Home Dirty", prompt: "Can you imagine God welcoming you before you get cleaned up?" },
      { day: 20, passage: "Jude 24", theme: "Kept From Falling", prompt: "What does dependence on God look like in the next twenty-four hours?" },
      { day: 21, passage: "Philippians 1:6", theme: "The Work Continues", prompt: "Freedom is usually a road, not a moment. What has changed in you that you do not want to dismiss?" },
    ],
  },
  gratitude: {
    slug: "gratitude",
    title: "Gratitude & Joy: The Abundance Mindset",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Gratitude is not denial. It is attention. Fourteen days on joy, contentment, abundance, and learning to notice God's goodness without pretending life is easy.",
    metaDescription:
      "Fourteen days on gratitude, joy, contentment, and choosing abundance over scarcity.",
    heroAlt: "Gratitude & Joy: The Abundance Mindset",
    ctaLabel: "Gratitude & Joy",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Joy and contentment" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Scarcity is not only about money. It is a way of seeing. It tells you there is not enough time, not enough love, not enough opportunity, not enough provision, not enough future. Gratitude does not erase pain, but it retrains attention to notice where grace is already at work.",
      "This journey helps you practice remembrance, contentment, celebration, and joy that can survive hard seasons. Zoe will keep moving you from vague positivity toward a more grounded, specific gratitude that changes the atmosphere of your life.",
    ],
    days: [
      { day: 1, passage: "Psalm 103:1-5", theme: "Remember on Purpose", prompt: "What goodness of God have you been living like it is normal?" },
      { day: 2, passage: "1 Thessalonians 5:16-18", theme: "In All, Not For All", prompt: "What can you thank God for without lying about the hard part?" },
      { day: 3, passage: "Luke 17:11-19", theme: "The One Who Came Back", prompt: "Where have you moved on too fast from mercy?" },
      { day: 4, passage: "Philippians 4:10-13", theme: "Contentment Learns", prompt: "What teaches your heart scarcity most quickly?" },
      { day: 5, passage: "James 1:17", theme: "Every Good Gift", prompt: "List five gifts from today that cost you nothing." },
      { day: 6, passage: "Psalm 16:11", theme: "Joy Near God", prompt: "What actually makes your soul come alive?" },
      { day: 7, passage: "John 2:1-11", theme: "Holy Abundance", prompt: "Where are you expecting lack because disappointment trained you to?" },
      { day: 8, passage: "Matthew 6:25-33", theme: "Enough for Today", prompt: "What daily bread have you overlooked because you were staring at tomorrow?" },
      { day: 9, passage: "Colossians 3:15-17", theme: "Let Thanks Run the House", prompt: "What would a more thankful atmosphere sound like in your home?" },
      { day: 10, passage: "Habakkuk 3:17-19", theme: "Joy With Empty Branches", prompt: "What remains true when visible abundance is not there?" },
      { day: 11, passage: "Deuteronomy 8:10-14", theme: "Do Not Forget in Full Seasons", prompt: "How does comfort make you less awake?" },
      { day: 12, passage: "Psalm 126", theme: "Laughter Returned", prompt: "What small sign of restoration deserves celebration?" },
      { day: 13, passage: "Luke 15:20-24", theme: "Join the Party", prompt: "Where are you resisting joy because cynicism feels safer?" },
      { day: 14, passage: "John 15:9-11", theme: "Joy That Can Stay", prompt: "What habit could make gratitude less occasional and more native?" },
    ],
  },
  patience: {
    slug: "patience",
    title: "Patience & Waiting: Trusting God's Timing",
    duration: "14 Days",
    difficulty: "introductory",
    description:
      "Waiting can expose everything you would rather not see. Fourteen days on patience, delay, hope, and learning to trust God's timing when nothing seems to move.",
    metaDescription:
      "Fourteen days on patience, delay, waiting, and learning to trust God's timing.",
    heroAlt: "Patience & Waiting: Trusting God's Timing",
    ctaLabel: "Patience & Waiting",
    stats: [
      { label: "Duration", value: "14 Days" },
      { label: "Focus", value: "Waiting with hope" },
      { label: "Passages", value: "14 readings" },
    ],
    body: [
      "Waiting has a way of exposing the things you hoped were not there: control, fear, entitlement, comparison, impatience, despair. Scripture does not glamorize delay, but it does show that God does deep work in people who learn how to wait without quitting.",
      "This journey helps you name what the delay is surfacing and practice hope sturdy enough to hold unanswered prayers. Zoe will keep reframing waiting, not as dead space, but as one of the places where trust gets formed.",
    ],
    days: [
      { day: 1, passage: "Psalm 27:13-14", theme: "Wait With Courage", prompt: "What are you tired of waiting for?" },
      { day: 2, passage: "Lamentations 3:25-26", theme: "Quiet Hope", prompt: "How do you usually act when God feels slow?" },
      { day: 3, passage: "Isaiah 40:28-31", theme: "Strength in the Delay", prompt: "What weakness is the waiting exposing in you?" },
      { day: 4, passage: "James 5:7-8", theme: "Farmer Time", prompt: "What are you digging up by checking too soon?" },
      { day: 5, passage: "Romans 8:22-25", theme: "Hope for What You Do Not See", prompt: "What unseen promise are you tempted to abandon?" },
      { day: 6, passage: "Psalm 130:5-6", theme: "Watchmen", prompt: "How does longing reshape a person?" },
      { day: 7, passage: "1 Samuel 13:8-14", theme: "The Cost of Impatience", prompt: "Where are you tempted to take over because God's timing offends you?" },
      { day: 8, passage: "Hebrews 6:12-15", theme: "Inherited Through Patience", prompt: "What promise needs endurance more than urgency?" },
      { day: 9, passage: "Luke 2:25-32", theme: "Simeon Waited Well", prompt: "What would faithful waiting look like over years, not just days?" },
      { day: 10, passage: "Ecclesiastes 7:8", theme: "The End Better Than the Beginning", prompt: "Where do you keep needing early closure?" },
      { day: 11, passage: "Psalm 37:7-9", theme: "Do Not Fret", prompt: "How is comparison making your waiting harder?" },
      { day: 12, passage: "John 11:1-6", theme: "Delays That Are Not Indifference", prompt: "What if God's delay is not God's absence?" },
      { day: 13, passage: "Galatians 6:9", theme: "Due Season", prompt: "What good seed have you sown that still looks invisible?" },
      { day: 14, passage: "Revelation 21:1-5", theme: "The Long Wait Ends", prompt: "Until the full repair comes, how do you want to become the kind of person who can wait with hope?" },
    ],
  },
} satisfies Record<string, JourneyContent>;

export type NewJourneySlug = keyof typeof journeyContent;
